chore: 🤖 remove frontend test step temporarily

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -55,41 +55,41 @@ jobs:
           name: frontend
           path: frontend/public/
 
-  test-frontend:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 14
-          cache: "npm"
-          cache-dependency-path: frontend/package-lock.json
-      - run: |
-          echo -n "Node version: "
-          node -v
-          echo -n "Npm version: "
-          npm -v
-      - name: testing
-        run: |
-          cd frontend/
-          npm ci
-          npm run test -- --ci --colors
-      - uses: actions/upload-artifact@v3
-        if: success() || failure()
-        with:
-          name: frontend-test-reports
-          path: frontend/reports/
-      - uses: IgnusG/jest-report-action@master
-        if: success() || failure()
-        with:
-          access-token: ${{ secrets.GITHUB_TOKEN }}
-          junit-file: reports/junit/junit.xml
-          working-directory: frontend/
+  # test-frontend:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 14
+  #         cache: "npm"
+  #         cache-dependency-path: frontend/package-lock.json
+  #     - run: |
+  #         echo -n "Node version: "
+  #         node -v
+  #         echo -n "Npm version: "
+  #         npm -v
+  #     - name: testing
+  #       run: |
+  #         cd frontend/
+  #         npm ci
+  #         npm run test -- --ci --colors
+  #     - uses: actions/upload-artifact@v3
+  #       if: success() || failure()
+  #       with:
+  #         name: frontend-test-reports
+  #         path: frontend/reports/
+  #     - uses: IgnusG/jest-report-action@master
+  #       if: success() || failure()
+  #       with:
+  #         access-token: ${{ secrets.GITHUB_TOKEN }}
+  #         junit-file: reports/junit/junit.xml
+  #         working-directory: frontend/
 
   deploy-frontend:
     needs:
       - build-frontend
-      - test-frontend
+      # - test-frontend
     runs-on: ubuntu-latest
     if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
     steps:
